Update plan.md
18F/ux-guide pull request #308
Opened 2022-12-14 16:51 UTC by bpdesigns

Updated content based to address [#126 Write section on ensuring diverse research participants](https://github.com/18F/ux-guide/issues/126). 

@jstrothman I've add a link to your Bias Identification workshop under "Writing a research plan > Team participation"

@MelissaBraxton I used your scratchpad in #126 as a starting point for these edits. 

In addition to a general review of the new text, I think the "Recruitment for Behavioral Diversity" might need to be added to or rewritten. I also think we could invite more participation in these edits, but thought I'd get your thoughts first.

2022-12-14 19:24 UTC, bpdesigns commented
@megan-moser, @Mtcarp, @em-herrick, @thebestsophist for your awareness and input.

2022-12-14 23:05 UTC, MelissaBraxton requested changes
Added some thoughts on refinements. 

I think it'd also be good to standardize or at least reduce the number of terms we use to talk about participants. It's a bit confusing that throughout this page, they're referred to as participant, interviewee, audience of interest, user of your service, target audience, target group, and participant group.

2022-12-14 23:05 UTC, MelissaBraxton commented on _pages/research/plan.md
> +Many government services support people through stressful situations. We learn the usability limitations of our designs when we get input from people with lived experience and diverse perspectives. W
I feel like there's a missed opportunity here to point how compensation helps us reduce bias in our research by not necessarily restricting participation to folks who have the privilege of being able to donate their time unpaid. I feel like that reason might be priority to stress over recompense for possibly asking folks to recall a stressful situation--esp. if we aren't balancing mention of this possible harm w/ content or at least linking to content on how we make sure in our research to reduce the risk of re-traumatizing participants.

2022-12-15 16:07 UTC, bpdesigns commented on _pages/research/plan.md
> +Running a [Bias Identification workshop(18F/GSA access only](https://docs.google.com/presentation/d/1l9UrizeRtiYrdclCRb7LIxPQF6XTvCI5A58ty-blRj4/edit#slide=id.ga8f8d32361_0_0)) helps teams account fo
updated

2022-12-15 16:13 UTC, bpdesigns commented on _pages/research/plan.md
> +Most of 18F’s design research depends on you directly interacting with people. Who those people are matters. Participants are the people you’ll recruit to take part in your research. For planning pur
Thoughts on this edit? "To make our products and services accessible to all, regardless of their abilities we need to take into account the degree of difficultly different groups might have when determining who to include in our research."

2022-12-15 16:16 UTC, bpdesigns commented on _pages/research/plan.md
> +Because of the time-limited nature of 18F engagements, participant groups can depend on the [type of research]({{site.baseurl}}/research/clarify-the-basics/#research-types) you're doing and where you
Updated as: "An opportunistic tactic like asking interviewees “who should I talk to next?” to get an initial understanding of what the relevant segments or audiences of interest. However, in later rounds of research make it a priority to learn from people within your audience of interest."

2022-12-15 16:17 UTC, bpdesigns commented on _pages/research/plan.md
> +People who look differently may behave similarly when using a product or service. Creating [Personas](https://methods.18f.gov/decide/personas/) allows you to define and distinguish between the way di
done

2022-12-15 16:17 UTC, bpdesigns commented on _pages/research/plan.md
> +Many government services support people through stressful situations. We learn the usability limitations of our designs when we get input from people with lived experience and diverse perspectives. W
great point.

2022-12-20 23:03 UTC, MelissaBraxton commented on _pages/research/plan.md
> +Many government services support people through stressful situations. We learn the usability limitations of our designs when we get input from people with lived experience and diverse perspectives. W
I think we need to revise this content before merging.

2022-12-21 21:57 UTC, bpdesigns commented on _pages/research/plan.md
> +Most of 18F’s design research depends on you directly interacting with people. Who those people are matters. Participants are the people you’ll recruit to take part in your research. For planning pur
@MelissaBraxton does this work better?

2022-12-28 17:00 UTC, bpdesigns commented on _pages/research/plan.md
> +Many government services support people through stressful situations. We learn the usability limitations of our designs when we get input from people with lived experience and diverse perspectives. W
ready for review @MelissaBraxton

2022-12-28 20:11 UTC, MelissaBraxton commented on _pages/research/plan.md
> +Compensation for participation in research allows us to get perspectives from people who have the privilege and flexibility to donate their time unpaid. We learn the usability limitations of our desi
There may be a typo here, but as written it sounds like compensation is for people who _can_ donate their time? 

What about something like: "Compensating participants helps us reduce bias in our research. Not compensating research participants can limit our participant pool to people who have the privilege and flexibility to donate their time unpaid."

2022-12-29 14:44 UTC, bpdesigns commented on _pages/research/plan.md
> +Compensation for participation in research allows us to get perspectives from people who have the privilege and flexibility to donate their time unpaid. We learn the usability limitations of our desi
That sounds good to me. I was missing a critical "don't" in the earlier version.

2022-12-29 14:48 UTC, bpdesigns commented on _pages/research/plan.md
> +Compensation for participation in research allows us to get perspectives from people who have the privilege and flexibility to donate their time unpaid. We learn the usability limitations of our desi
@MelissaBraxton updated with your edit. With your review I think the content is ready to merge.

2022-12-29 15:16 UTC, bpdesigns commented
Following the fail on verifying links I see "Error: in _site/research/lead/index.html" and  "Error: in _site/research/plan/index.html" 

I only updated the Plan file. @mgwalker can we cowork on troubleshooting this next week?

2023-01-03 23:19 UTC, MelissaBraxton commented on _pages/research/plan.md
> +Most of 18F’s design research depends on you directly interacting with people. Who those people are matters. Participants are the people you’ll recruit to take part in your research. For planning pur
Yep!

2023-01-03 23:20 UTC, MelissaBraxton approved these changes

2023-01-03 23:31 UTC, MelissaBraxton commented on _pages/research/plan.md
> +Because of the time-limited nature of 18F engagements, participant groups can depend on the [type of research]({{site.baseurl}}/research/clarify-the-basics/#research-types) you're doing and where you
There's a typo here. 

Suggested edit:
"An opportunistic tactic like asking interviewees “who should I talk to next?” can help you get an initial understanding of the different user groups who's needs you must design for. You may need to focus later rounds of research on learning directly from people within these user groups."

2023-01-03 23:31 UTC, MelissaBraxton commented on _pages/research/plan.md
> +Compensation for participation in research allows us to get perspectives from people who have the privilege and flexibility to donate their time unpaid. We learn the usability limitations of our desi
LGTM!

2023-01-04 16:57 UTC, bpdesigns commented on _pages/research/plan.md
> +Because of the time-limited nature of 18F engagements, participant groups can depend on the [type of research]({{site.baseurl}}/research/clarify-the-basics/#research-types) you're doing and where you
@MelissaBraxton updated and ready for your review.

2023-01-05 14:07 UTC, jstrothman commented
I updated the frames of reference deck to be a stand-alone activity--it was a deck with some framing slides for a Research Guild discussion. As a result, I updated the link to the deck to go to the first slide instead of mid-way through. I also updated the frames of reference form (not directly linked in this page) to have some background info, now that it's been [linked to from CFPB](https://cfpb.github.io/design-system/guidelines/setting-the-foundation#frames-of-reference).

I'd like to do a bit more review later today, if that's okay.

2023-01-05 16:06 UTC, bpdesigns commented
Sounds good. Thanks @jstrothman

2023-01-09 16:38 UTC, jstrothman reviewed
@bpdesigns The previous changes look good to me! I made a bunch of edits, so I'm not using the 'approve' feature in this review as you may want to revert some of the edits or make further adjustments

2023-01-09 20:03 UTC, bpdesigns reviewed
These look great. Thanks @jstrothman

2023-01-10 15:13 UTC, bpdesigns commented
Thanks @jstrothman and @MelissaBraxton for reviewing all this text!

2023-01-10 15:18 UTC, bpdesigns reviewed
@MelissaBraxton can you approve this latest commit? Julie updated the text. It looks good to me but as the original author of the commit I can't approve it.

2023-01-27 18:47 UTC, merged