Update links and remove Privacy Impact Assessment
18F/ux-guide pull request #403
Opened 2023-04-25 17:25 UTC by janelx

## Description of changes

Update links and removed direct mentions of Privacy Impact Assessment

## Reviewers:
- [ ] @MelissaBraxton : please review changes
- [ ] @bpdesigns : please review changes

2023-04-28 19:17 UTC, bpdesigns requested changes
Please see the inline comment around line 50

2023-04-28 19:17 UTC, bpdesigns commented on _pages/research/privacy.md
>  - Whenever you collect PII, store it digitally on [GSA’s approved systems for PII](https://www.gsa.gov/reference/gsa-privacy-program/privacy-impact-assessments-pia) and actively remove access to PII
the link for storing PII should be the webpage on [SORNs](https://www.gsa.gov/reference/gsa-privacy-program/systems-of-records-privacy-act/system-of-records-notices-sorns-privacy-act) not PIA

2023-05-01 13:19 UTC, bpdesigns commented
Hi @janelx I added one comment that needs to be updated before approval.

2023-05-01 17:36 UTC, bpdesigns commented on _pages/research/privacy.md
In place of the PIA, please add 

"18F complies with the Privacy Act by following the information practices outlined in our [Privacy Act Statement for Design Research](https://www.gsa.gov/reference/gsa-privacy-program/privacy-act-statement-for-design-research on GSA.gov)."

2023-05-01 17:38 UTC, bpdesigns commented
Hi @janelx in chatting with @MelissaBraxton we noted the opportunity to call out the Privacy Act Statement for Design Research

2023-05-01 17:47 UTC, janelx commented on _pages/research/privacy.md
@bpdesigns Which sentence would you like to replace? It this one: "_The following guidelines, drawn from our Privacy Impact Assessment for Design Research, help us build trust and protect privacy. This list isn’t exhaustive, but it’s a good place to start:"_?

2023-05-01 17:58 UTC, bpdesigns commented on _pages/research/privacy.md
Apologies. I think I was unclear. Please add this sentence into the content you have. It replaces what was removed from lines 38-40 below.

2023-05-02 16:07 UTC, janelx commented
@bpdesigns I believe I made all the requested updates and it's ready for another review. Thank you!

2023-05-02 16:55 UTC, bpdesigns approved these changes

2023-05-04 19:09 UTC, merged